name: Not Found Bot

on:
  schedule:
    - cron: "0 5 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fix links
        uses: tmcw/notfoundbot@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
